### ISSUE TITLE
Expose the substring search functions to WASM

### ISSUE THREAD

**Issue by BobWall23** [IronCoreLabs/recrypt-wasm-binding#23]
Pull in the `ironcore-search-helpers` and expose functions. Requires these steps:

- [ ] Upgrade to recrypt 0.11
- [ ] Expose the `generate_hashes_for_string_with_padding` and `generate_hashes_for_string` functions, behind a feature flag.

**Comment by giarc3** [comment]
We decided to not use a feature flag in Rust because building without the flag would cause a compile error in TypeScript for referencing functions that don't exist.
