### ISSUE TITLE
Compile on newer wasm bindgen

### ISSUE THREAD

**Issue by skeet70** [IronCoreLabs/recrypt-wasm-binding#43]
I'm not sure which version of `wasm-bindgen` is running in CI, but my local attempts with `wasm-bindgen 0.2.74 (d1d64200a)` failed to compile.

It looks like there need to be significant reworks in the `fixBindgenShim.js` code, as the output of `wasm-bindgen` has changed pretty significantly itself. 

```js
function removeNodeJSFunctions() {
    const shimJS = fs.readFileSync(SOURCE_JS_FILE, "utf8");

    //Replace the entire __wbg_require and randomFillSync method that is auto generated in the output.
    const codeWithoutNode = shimJS
        .replace(/\nexport function __wbg_require_[a-f0-9]*[(]arg0, arg1[)] {[^}]*};\n/, "")
        .replace(/\nexport function __wbg_randomFillSync_[a-f0-9]*[(]arg0, arg1, arg2[)] {[^}]*};\n/, "");

    if (codeWithoutNode.includes("require(") || codeWithoutNode.includes("randomFillSync")) {
        throw new Error("Replacement of NodeJS import and/or randomFillSync functions failed!");
    }
    fs.writeFileSync(SOURCE_JS_FILE, codeWithoutNode, "utf8");
}
```

That worked to fix the `removeNodeJSFunctions` breakage, but it looks like each of the other replacement functions may have changed as well.

According to https://caniuse.com/cryptography, WebCrypto support in WebWorkers was added to Edge at the end of 2018, we may now be safe to drop all the stuff we're doing in the shim to use `Recrypt.setRandomSeed` instead in Edge, which would simplify the shim drastically.

**Comment by BobWall23** [comment]
Should focus on removing the fix-bindgen stuff. Use the webcrypto support in Edge, rely on the webpack fix that was the other reason we need fix-bindgen.
